### ISSUE TITLE
Proposals for new design

### ISSUE THREAD

**Issue by teevik** [DevvitIO/DevvitIO.github.io#10]
I saw a discussion about this on the discord, and thought i would open up a issue for it

Anyone who wants to suggest a new design to use can post here, if they want to

**Comment by teevik** [comment]
I'll also try to make a design

**Comment by sc0ttr0berts0n** [comment]
You should discuss your goals for the new design. What do you wan the site to accomplish, and how do you get it front and center through your design?

**Comment by teevik** [comment]
I'm not sure really. The content would be the same as the current one, so mostly just aesthetics

**Comment by sc0ttr0berts0n** [comment]
I’d argue the goal of the site is to communicate that we are a discord community and a place for new devs to socialize with other developers and a place to collaborate. We should forward people to the discord and show our active projects. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sc0ttr0berts0n** [comment]
As we do. But let’s make sure that the design best accomplished those goals. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Tor020** [comment]
In general the website just looks very bland imo, it serves its purpose but as a webdev community we want to look like we're not amateurs, imo. Something something competence etc.

I don't think that @teevik is saying that the website's purpose will change at all with his suggestions or design implementations, more-so that he is saying the website can be made to look more aesthetically pleasing while accomplishing the same goals @sc0ttr0berts0n

**Comment by sc0ttr0berts0n** [comment]
well if the goal of the site is to portray an image of competence than we must design it as such. That’s all I’m saying.

**Comment by Tor020** [comment]
> well if the goal of the site is to portray an image of competence than we must design it as such. That’s all I’m saying.

You probably meant 

> well if the goal **of the design** of the site is to portray an image of competence than we must design it as such. That’s all I’m saying.

and if so, ye ur rite

Imma go into a little bit of detail though so that anyone else who sees this set of messages would be able to get themselves up to speed.
_____
## The Goal of the website

To inform an audience who have never previously encountered Devvit or are seeking more information about what Devvit is. It should inform the audience the basics of what the purpose of the organization and have all of the information a newcomer would want if they wanted to get involved, available to them.

## The Underlying Tone

A person who comes to the website should get the impression, based upon the design that we know what we're doing and that there isn't anything amateurish about the organization. ie: what I would describe as competence
______

In case you hadn't seen this issue [about](https://github.com/DevvitIO/DevvitIO.github.io/issues/6)

that ideally is our about page/what Devvit is

If nebody has question feel free 2 ask

**Comment by sc0ttr0berts0n** [comment]
Just to be clear, I 100% meant the goal of the site. The design should help to accomplish the goal of the website. The question is, what do we design to meet these goals. Visual Communication. I'm not trying to make this a lesson or debate what I'm trying to say. I'm just. trying. to. talk. about. the. sites. design.

I think the hero area in the current one is wasted space. And if were trying to convey professionalism and capability perhaps the area is better utilized with an HTML canvas background, or something technically complicated to set the mood. Something nobody has seen before.

I think the opening line (An Open Source community that started from people's...) should be more active in its messaging. It should encourage the user to join, not just say what were about. Say its for people who share these sentiments. The message is good, just it could be a bit more steered towards the reader.

Unless its a bad thing, maybe some meta data about the projects. (Current contributors, commits, etc). I'd ideally want this to suggest that these are active, lively communities that you could help out in. Maybe stats and facts is a way to present each of the projects as such.

Side note, that online users list for discord could be very useful for generating some sort of HTML canvas background showing us all hustling and bustling. Could get people excited about the community. I may work on that if people think its a good idea. I see all the users and their names floating in space like little atoms.

**Comment by LucasProgrammierStube** [comment]
I like this atom idea. If you place the names so they look like several atoms I would design the whole website like natural science. Every project as an element etc.

**Comment by LucasProgrammierStube** [comment]
In the design of a periodic table
Element "rad", "cms" etc.

**Comment by Tor020** [comment]
This issue was moved to DevvitIO/Devvit_2.0#4
